version: '3.3'

services:
  data-db:
    image: postgres:9.6
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'data'
    ports:
      - '5432:5432'
    volumes:
      - ../.data/pg96:/var/lib/postgresql/data/
    container_name: data
